const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const icon = (name) => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const mixes = [
  {id:'morning',title:'Slow Morning Club',description:'No rush. Just a little room to breathe.',mood:'chill',art:'peach',word:'slow<br><em>mornings.</em>',mark:'am.',label:'TAKE YOUR TIME',bottom:'A SOFTER START TO YOUR DAY',tracks:12,minutes:38,track:'Soft Landing',artist:'The Slow Morning Sessions',notes:[196,246.94,293.66,369.99],tempo:540},
  {id:'focus',title:'A State of Flow',description:'Find the space between distractions.',mood:'focus',art:'purple',word:'a state<br>of <em>flow.</em>',mark:'flow.',label:'HEAD DOWN. WORLD OFF.',bottom:'YOUR SPACE TO GO A LITTLE DEEPER',tracks:16,minutes:52,track:'Between the Lines',artist:'A State of Flow',notes:[174.61,220,261.63,329.63],tempo:640},
  {id:'sunshine',title:'Good Things Coming',description:'A soundtrack for your sunny side.',mood:'energy',art:'orange',word:'GOOD<br>THINGS<br>COMING.',mark:'good.',label:'TURN IT UP. FEEL IT ALL.',bottom:'A LITTLE DOSE OF OPTIMISM',tracks:14,minutes:45,track:'Golden Hour',artist:'Good Things Coming',notes:[261.63,329.63,392,523.25],tempo:340},
  {id:'night',title:'When the City Sleeps',description:'For thoughts that only arrive at 2am.',mood:'night',art:'blue',word:'when the<br>city<br><em>sleeps.</em>',mark:'2am.',label:'THE OTHER SIDE OF MIDNIGHT',bottom:'STAY UP. SINK IN.',tracks:10,minutes:34,track:'Blue Window',artist:'When the City Sleeps',notes:[146.83,174.61,220,293.66],tempo:710}
];
const stations = [
  {id:'static',freq:'88.1',name:'Morning Static',genre:'Ambient',show:'First Light',host:'Ines Okafor',description:'Warm tape hiss and slow chords for the hour before the world wakes up.',mix:'morning',art:'peach',accent:'#e8bcb0',listeners:842,notes:[196,246.94,293.66,369.99],tempo:600},
  {id:'deepwork',freq:'91.7',name:'Deep Work FM',genre:'Focus',show:'Heads Down',host:'Theo Marsh',description:'Steady pulses, zero lyrics. The station that keeps your tabs closed.',mix:'focus',art:'purple',accent:'#b1a0d1',listeners:2310,notes:[164.81,207.65,246.94,329.63],tempo:680},
  {id:'sunny',freq:'94.3',name:'Sunny Side Up',genre:'Feel-good',show:'The Bright Hour',host:'Mara Ruiz',description:'Bright, bouncy and a little bit cheesy. Exactly what the afternoon needs.',mix:'sunshine',art:'orange',accent:'#f2a65a',listeners:1675,notes:[293.66,369.99,440,587.33],tempo:320},
  {id:'waveform',freq:'98.4',name:'Waveform Radio',genre:'Eclectic',show:'Selectors Live',host:'the Waveform selectors',description:'Our flagship station. Hand-picked, never shuffled by a machine, always a little unexpected.',mix:'sunshine',art:'orange',accent:'#d6f879',listeners:4128,notes:[220,277.18,329.63,440],tempo:460},
  {id:'nightbus',freq:'102.9',name:'Night Bus',genre:'After dark',show:'Last Stop',host:'Juno Park',description:'Neon-lit and unhurried. For long rides home and thoughts that arrive at 2am.',mix:'night',art:'blue',accent:'#7887c3',listeners:1204,notes:[138.59,164.81,207.65,277.18],tempo:760},
  {id:'lowtide',freq:'106.5',name:'Low Tide',genre:'Chill',show:'Slow Water',host:'Sami Lind',description:'Gentle and wide open, like the sea on a quiet evening. Lie back and let it drift.',mix:'morning',art:'blue',accent:'#8fd3c7',listeners:968,notes:[185,233.08,277.18,369.99],tempo:820}
];
let saved;
try { saved = new Set(JSON.parse(localStorage.getItem('waveform-saved') || '[]')); } catch { saved = new Set(); }
let currentView = 'discover', filter = 'all', current = 0, playing = false, elapsed = 0, shuffle = false, repeat = false;
let audio, master, noteTimer, progressTimer, noteIndex = 0, lastVolume = 55, station = null, featured = 3;
const activeVoices = new Set();
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('#toast').classList.remove('visible'), 2600); }
function updateSaved() { try { localStorage.setItem('waveform-saved',JSON.stringify([...saved])); } catch {} $('.library-count').textContent = saved.size; const selected = saved.has(mixes[current].id); $('#player-save').classList.toggle('saved',selected); $('#player-save').setAttribute('aria-pressed',selected); }
function saveMix(id) { saved.has(id) ? saved.delete(id) : saved.add(id); updateSaved(); renderMixes(); toast(saved.has(id) ? 'Added to your library. Good taste.' : 'Removed from your library.'); }
function renderMixes() {
  const search = $('#search').value.toLowerCase().trim();
  const visible = mixes.filter(m => (filter === 'all' || m.mood === filter) && (currentView !== 'library' || saved.has(m.id)) && `${m.title} ${m.description} ${m.mood} ${m.track}`.toLowerCase().includes(search));
  const isPlaying = (m) => playing && !station && mixes[current].id === m.id;
  $('#mix-grid').innerHTML = visible.map((m,i) => `<article class="mix-card" style="animation-delay:${i*40}ms"><div class="album-art art-${m.art}"><span class="album-topline">${m.label}</span><span class="album-word">${m.word}</span><span class="album-bottomline">${m.bottom}</span><button class="album-play ${isPlaying(m) ? 'is-playing' : ''}" data-play="${m.id}" aria-label="${isPlaying(m) ? 'Pause' : 'Play'} ${m.title}">${icon(isPlaying(m) ? 'pause':'play')}</button></div><div class="album-meta"><h3>${m.title}</h3><button class="icon-button ${saved.has(m.id) ? 'saved' : ''}" data-save="${m.id}" aria-label="${saved.has(m.id)?'Unsave':'Save'} ${m.title}" aria-pressed="${saved.has(m.id)}">${icon('heart')}</button></div><p class="album-description">${m.description}</p><p class="album-info"><span>${m.tracks} tracks</span><span>·</span><span>${m.minutes} min</span><span>·</span><span>Waveform selects</span></p></article>`).join('');
  $('#empty-state').hidden = visible.length > 0;
  $('#mix-count').textContent = `${visible.length} handpicked mix${visible.length === 1 ? '' : 'es'}`;
  if(currentView === 'library' && saved.size === 0) { $('#empty-state h3').textContent = 'Your next favorites live here.'; $('#empty-state p').textContent = 'Tap the heart on a mix to make it part of your rotation.'; } else { $('#empty-state h3').textContent = 'A little too off the radar.'; $('#empty-state p').textContent = 'Try another mood or search to find your next sound.'; }
  $$('[data-play]').forEach(b => b.addEventListener('click',() => playMix(mixes.findIndex(m => m.id === b.dataset.play))));
  $$('[data-save]').forEach(b => b.addEventListener('click',() => saveMix(b.dataset.save)));
}
function setFilter(value) { filter = value; $$('.filter').forEach(b => b.classList.toggle('active',b.dataset.filter === value)); renderMixes(); }
function setView(view) { currentView = view; $$('.nav-item').forEach(b => { b.classList.toggle('active',b.dataset.view === view); b.setAttribute('aria-current',b.dataset.view === view ? 'page' : 'false'); }); $('#breadcrumb-view').textContent = {discover:'Discover',radio:'Radio',library:'Your library'}[view]; $('#page-title').innerHTML = {discover:'Find your frequency<span>.</span>',radio:'Always on your wavelength<span>.</span>',library:'Your kind of sound<span>.</span>'}[view]; $('#mix-heading').textContent = {discover:"What's your headspace?",radio:'Pick a station. Stay a while.',library:'The sounds you come back to.'}[view]; $('.hero').hidden = view !== 'discover'; $('.bottom-grid').hidden = view !== 'discover'; $('.discover-section').hidden = view === 'radio'; $('#radio-view').hidden = view !== 'radio'; setFilter('all'); renderRadio(); closeMenu(); }
const listeners = (count) => count >= 1000 ? `${(count/1000).toFixed(1)}k` : String(count);
function renderRadio() {
  const s = stations[featured], live = (x) => playing && station === x, search = $('#search').value.toLowerCase().trim();
  $('#on-air').style.setProperty('--accent',s.accent); $('#on-air').classList.toggle('is-live',live(s));
  $('#on-air-freq').textContent = s.freq; $('#radio-title').textContent = s.name; $('#on-air-desc').textContent = s.description; $('#on-air-host').textContent = `${s.show} · with ${s.host}`; $('#on-air-listeners').textContent = `${listeners(s.listeners)} listening`;
  $('#radio-play').innerHTML = `${icon(live(s)?'pause':'play')}${live(s)?'Pause':station === s?'Resume':'Tune in'}`;
  $('#dial-needle').style.left = `${(parseFloat(s.freq)-88)/20*100}%`;
  $$('.dial-mark').forEach(mark => mark.classList.toggle('active',mark.dataset.mark === s.id));
  const visible = stations.filter(x => `${x.name} ${x.genre} ${x.show} ${x.host} ${x.freq}`.toLowerCase().includes(search));
  $('#station-grid').innerHTML = visible.map((x,i) => `<button class="station-card ${live(x)?'is-live':''} ${x === s?'is-featured':''}" style="--accent:${x.accent};animation-delay:${i*40}ms" data-station="${x.id}" aria-pressed="${live(x)}" aria-label="${live(x)?'Pause':'Tune in to'} ${x.name}, ${x.freq} FM"><span class="station-top"><span>${x.genre}</span><span class="station-badge">${live(x)?'<span class="mini-eq"><i></i><i></i><i></i></span>ON AIR':'LIVE'}</span></span><span class="station-freq">${x.freq}<small>FM</small></span><span class="station-name">${x.name}</span><span class="station-show">${x.show} · ${x.host}</span><span class="station-foot"><span><span class="live-dot"></span>${listeners(x.listeners)} listening</span><span class="station-play">${icon(live(x)?'pause':'play')}</span></span></button>`).join('');
  $('#radio-empty').hidden = visible.length > 0;
  $('#station-count').textContent = `${visible.length} station${visible.length === 1 ? '' : 's'} live`;
  const hour = new Date().getHours();
  $('#schedule-list').innerHTML = [0,1,2,3].map(n => { const x = stations[(featured+n)%stations.length]; return `<li class="${n === 0 ? 'is-now' : ''}" style="--accent:${x.accent}"><time>${n === 0 ? 'NOW' : `${String((hour+n)%24).padStart(2,'0')}:00`}</time><div><strong>${x.show}</strong><span>${x.name} · with ${x.host}</span></div><span class="schedule-freq">${x.freq} FM</span><button class="icon-button" data-station="${x.id}" aria-label="Tune in to ${x.name}">${icon(live(x)?'pause':'play')}</button></li>`; }).join('');
}
function tuneStation(id) { const index = stations.findIndex(x => x.id === id), s = stations[index]; featured = index; if(station === s) { setPlaying(!playing); return; } station = s; current = mixes.findIndex(m => m.id === s.mix); elapsed = 0; noteIndex = 0; setPlaying(true); if(playing) toast(`Tuned to ${s.freq} FM · ${s.name}`); }
function initializeAudio() { if(!audio) { const Audio = window.AudioContext || window.webkitAudioContext; if(!Audio) { toast('Audio previews are unavailable in this browser.'); return false; } audio = new Audio(); master = audio.createGain(); master.gain.value = Number($('#volume').value)/100*0.28; master.connect(audio.destination); } if(audio.state === 'suspended') audio.resume().catch(() => toast('Click play again to enable audio.')); return true; }
function makeNote(frequency, delay, duration, type='sine', strength=.16) { const oscillator = audio.createOscillator(), envelope = audio.createGain(); oscillator.type = type; oscillator.frequency.value = frequency; const now = audio.currentTime + delay; envelope.gain.setValueAtTime(0,now); envelope.gain.linearRampToValueAtTime(strength,now+.035); envelope.gain.exponentialRampToValueAtTime(.0001,now+duration); oscillator.connect(envelope); envelope.connect(master); oscillator.start(now); oscillator.stop(now+duration+.05); activeVoices.add(oscillator); oscillator.onended = () => { activeVoices.delete(oscillator); oscillator.disconnect(); envelope.disconnect(); }; }
function tickNotes() { if(!playing) return; const m = station || mixes[current], sequence = [0,2,1,3,2,0,3,1]; makeNote(m.notes[sequence[noteIndex%8]],0,1.7,'sine',.2); if(noteIndex%4 === 0) makeNote(m.notes[0]/2,0,2.6,'sine',.15); if(noteIndex%2 === 0) makeNote(m.notes[(noteIndex+1)%4]*2,.12,.8,'triangle',.035); noteIndex++; }
function stopAudio() { clearInterval(noteTimer); clearInterval(progressTimer); for(const voice of activeVoices) { try { voice.stop(); } catch {} } activeVoices.clear(); }
function refreshPlayer() { const m = mixes[current]; $('#track-title').textContent = station ? station.name : m.track; $('#track-artist').textContent = station ? `${station.freq} FM · ${station.show}` : m.artist; $('#player-art').className = `mini-art art-${station ? station.art : m.art}`; $('#player-art').innerHTML = `<span>${station ? 'fm.' : m.mark}</span>`; $('.audio-label').innerHTML = `${icon('wave')}${station ? 'LIVE RADIO' : 'ORIGINAL PREVIEW'}`; $('#progress').disabled = !!station; $('#play-toggle').innerHTML = icon(playing?'pause':'play'); $('#play-toggle').classList.toggle('is-playing',playing); $('#play-toggle').setAttribute('aria-label',playing?'Pause':'Play'); $('#hero-play').innerHTML = `${icon(playing && !station?'pause':'play')}${playing && !station?'Pause the mix':'Play the mix'}`; document.body.classList.toggle('playing',playing); updateProgress(); updateSaved(); renderMixes(); renderRadio(); }
function updateProgress() { $('#elapsed').textContent = `${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`; $('#progress').value = station ? 180 : elapsed; $('#progress').style.setProperty('--progress',station ? '100%' : `${elapsed/180*100}%`); $('#duration').textContent = station ? 'LIVE' : '3:00'; }
function setPlaying(value) { if(value && !initializeAudio()) return; playing = value; stopAudio(); if(playing) { tickNotes(); noteTimer = setInterval(tickNotes,(station || mixes[current]).tempo); progressTimer = setInterval(() => { elapsed++; if(!station && elapsed>=180) { if(repeat){elapsed=0;noteIndex=0;} else { skipTrack(1); } } updateProgress(); },1000); } refreshPlayer(); }
function playMix(index) { if(index === current && !station) setPlaying(!playing); else { station = null; current = index; elapsed = 0; noteIndex = 0; setPlaying(true); } }
function skipTrack(direction) { const list = station ? stations : mixes, at = station ? stations.indexOf(station) : current, next = shuffle ? (at + 1 + Math.floor(Math.random()*(list.length-1)))%list.length : (at+direction+list.length)%list.length; if(station) { featured = next; station = stations[next]; current = mixes.findIndex(m => m.id === station.mix); } else current = next; elapsed=0;noteIndex=0;const wasPlaying=playing;stopAudio();if(wasPlaying)setPlaying(true);else refreshPlayer(); }
function openDialog(html) { $('#dialog-content').innerHTML = html; $('#info-dialog').showModal(); }
function closeMenu() { document.body.classList.remove('menu-open'); $('#menu-toggle').setAttribute('aria-expanded','false'); }
$$('[data-view]').forEach(b => b.addEventListener('click',() => setView(b.dataset.view)));
$$('[data-filter]').forEach(b => b.addEventListener('click',() => setFilter(b.dataset.filter)));
$$('[data-mood]').forEach(b => b.addEventListener('click',() => { if(currentView !== 'discover') setView('discover');setFilter(b.dataset.mood);closeMenu();$('.discover-section').scrollIntoView({behavior:'smooth',block:'start'}); }));
$('#search').addEventListener('input',() => { renderMixes(); renderRadio(); });
$('#play-toggle').addEventListener('click',() => setPlaying(!playing));
$('#hero-play').addEventListener('click',() => playMix(current));
$('#daily-play').addEventListener('click',() => playMix(2));
$('#previous').addEventListener('click',() => skipTrack(-1));
$('#next').addEventListener('click',() => skipTrack(1));
$('#progress').addEventListener('input',event => { if(station) return; elapsed=Number(event.target.value);updateProgress(); });
$('#volume').addEventListener('input',event => { const volume = Number(event.target.value); event.target.style.setProperty('--progress',`${volume}%`); if(master)master.gain.setTargetAtTime(volume/100*.28,audio.currentTime,.03);$('#mute').setAttribute('aria-label',volume===0?'Unmute':'Mute');$('#mute').style.opacity=volume===0?'.45':'1'; });
$('#mute').addEventListener('click',() => { const input=$('#volume');if(Number(input.value)>0){lastVolume=Number(input.value);input.value=0;}else input.value=lastVolume || 55;input.dispatchEvent(new Event('input')); });
$('#shuffle').addEventListener('click',() => { shuffle=!shuffle;$('#shuffle').setAttribute('aria-pressed',shuffle);toast(shuffle?'Shuffle on. A little surprise is good.':'Shuffle off.'); });
$('#repeat').addEventListener('click',() => { repeat=!repeat;$('#repeat').setAttribute('aria-pressed',repeat);toast(repeat?'On repeat. We get it.':'Repeat off.'); });
$('#player-save').addEventListener('click',() => saveMix(mixes[current].id));
function showAll() { $('#search').value='';setView('discover');setFilter('all');$('.discover-section').scrollIntoView({behavior:'smooth',block:'start'}); }
$('#view-all').addEventListener('click',showAll);$('#clear-search').addEventListener('click',showAll);
$('#menu-toggle').addEventListener('click',() => { const open=document.body.classList.toggle('menu-open');$('#menu-toggle').setAttribute('aria-expanded',open); });
document.addEventListener('click',event => { if(document.body.classList.contains('menu-open') && !event.target.closest('#sidebar') && !event.target.closest('#menu-toggle'))closeMenu(); });
document.addEventListener('keydown',event => { if(event.key==='Escape')closeMenu();if(event.key==='/' && !['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();$('#search').focus();}if(event.code==='Space' && !['INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName) && !$('#info-dialog').open){event.preventDefault();setPlaying(!playing);} });
$('#dialog-close').addEventListener('click',() => $('#info-dialog').close());
$('#info-dialog').addEventListener('click',event => { if(event.target === $('#info-dialog')){const r=event.target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.target.close();} });
$('#about-button').addEventListener('click',() => openDialog('<span class="dialog-mark">w.</span><p class="eyebrow">THE HUMAN TOUCH</p><h2>A good kind of different.</h2><p>Waveform is a little corner of the internet for people who love the feeling of finding something new. Every mix has its own headspace, from the first light of morning to the last train home.</p><p>Press play to hear original instrumental previews, made right in your browser. Save a few favorites and make yourself at home.</p>'));
function showProfile(){openDialog(`<div class="avatar">J</div><h2>Your personal space.</h2><p>Hey, Jamie. Your favorites stay saved on this device, ready for your next listening session.</p><div class="dialog-stats"><div><strong>${saved.size}</strong><span>Saved mixes</span></div><div><strong>4</strong><span>New discoveries</span></div></div>`);}
$('#profile').addEventListener('click',showProfile);$('#top-profile').addEventListener('click',showProfile);
$('#add-playlist').addEventListener('click',() => { openDialog('<p class="eyebrow">MAKE IT YOURS</p><h2>A new little obsession.</h2><form id="playlist-form"><label for="playlist-name">Give your playlist a name</label><input id="playlist-name" placeholder="Sunday kind of feeling" maxlength="36" required autocomplete="off"><button class="button button-lime" type="submit">Create playlist</button></form>');$('#playlist-name').focus();$('#playlist-form').addEventListener('submit',event => { event.preventDefault();const name=$('#playlist-name').value.trim();if(!name)return;const button=document.createElement('button');button.className='collection';const art=document.createElement('span');art.className='collection-art art-purple';const text=document.createElement('span');text.textContent=name;const small=document.createElement('small');small.textContent='Your saved mixes';text.append(small);button.append(art,text);button.addEventListener('click',() => {setView('library');toast(`${name} · Your saved mixes`);});$('#collections').append(button);$('#info-dialog').close();toast('Your playlist is ready. Save a mix to start your rotation.'); }); });
$('.brand').addEventListener('click',event => {event.preventDefault();setView('discover');window.scrollTo({top:0,behavior:'smooth'});});
$('#radio-view').addEventListener('click',event => { const button = event.target.closest('[data-station]'); if(button) tuneStation(button.dataset.station); });
$('#radio-play').addEventListener('click',() => tuneStation(stations[featured].id));
$('#radio-clear').addEventListener('click',() => { $('#search').value = ''; renderMixes(); renderRadio(); });
$('#eq').innerHTML = Array.from({length:32},(_,i) => `<i style="--h:${28+Math.round(Math.abs(Math.sin(i*1.7))*62)}%;--d:${(i%7)*-.13}s"></i>`).join('');
$('#dial-track').insertAdjacentHTML('beforeend',stations.map(x => `<span class="dial-mark" data-mark="${x.id}" style="left:${(parseFloat(x.freq)-88)/20*100}%;--accent:${x.accent}"></span>`).join(''));
window.addEventListener('pagehide',stopAudio);
updateSaved();renderMixes();renderRadio();
